version: '3.8'

# Docker Compose configuration for building and running Langfuse
# This extends the base infrastructure services

services:
  # Build Langfuse from Agent A's fork
  langfuse:
    build:
      context: ../../../sambatv-ai-platform
      dockerfile: web/Dockerfile
      args:
        # Disable telemetry and non-essential features for build
        NEXT_PUBLIC_POSTHOG_KEY: ""
        NEXT_PUBLIC_POSTHOG_HOST: ""
        NEXT_PUBLIC_SIGN_UP_DISABLED: "false"
        NEXT_TELEMETRY_DISABLED: "1"
        NODE_OPTIONS: "--max-old-space-size=4096"
    image: sambatv-ai-platform:staging
    container_name: sambatv-ai-platform
    env_file:
      - .env.staging
    environment:
      # Override specific values for container runtime
      DATABASE_URL: postgresql://langfuse:${POSTGRES_PASSWORD:-staging_secure_password_changeme}@postgres:5432/langfuse
      REDIS_URL: redis://:${REDIS_PASSWORD:-staging_redis_password_changeme}@redis:6379/0
      NEXTAUTH_URL: https://staging-ai.sambatv.com
      PORT: 3000
    ports:
      - "3001:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - langfuse-network

  # Build Langfuse worker
  langfuse-worker:
    build:
      context: ../../../sambatv-ai-platform
      dockerfile: worker/Dockerfile
      args:
        NODE_OPTIONS: "--max-old-space-size=2048"
    image: sambatv-worker:staging
    container_name: sambatv-worker
    env_file:
      - .env.staging
    environment:
      DATABASE_URL: postgresql://langfuse:${POSTGRES_PASSWORD:-staging_secure_password_changeme}@postgres:5432/langfuse
      REDIS_URL: redis://:${REDIS_PASSWORD:-staging_redis_password_changeme}@redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - langfuse-network

networks:
  langfuse-network:
    external: true