global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'sambatv-ai-platform'
    environment: 'production'

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - "alerts/*.yml"

scrape_configs:
  # Node Exporter
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          instance: 'langfuse-server'

  # PostgreSQL Exporter
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          instance: 'langfuse-postgres'

  # Redis Exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          instance: 'langfuse-redis'

  # Langfuse Application Metrics
  - job_name: 'langfuse'
    static_configs:
      - targets: ['langfuse:3000']
        labels:
          app: 'sambatv-ai-platform'
    metrics_path: '/api/metrics'

  # Nginx Exporter
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
        labels:
          instance: 'langfuse-nginx'

  # Docker containers
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          instance: 'langfuse-containers'